### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by ghost** [dmillerw/AlchemicalBling#1]
I got this crash while attacking a cow. I do not have any splash potions.

```
net.minecraft.util.ReportedException: Exception while ticking a block
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:937) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_40]
Caused by: java.lang.NullPointerException
        at net.minecraft.entity.projectile.EntityThrowable.<init>(EntityThrowable.java:53) ~[zk.class:?]
        at net.minecraft.entity.projectile.EntityPotion.<init>(EntityPotion.java:41) ~[zo.class:?]
        at net.minecraft.entity.projectile.EntityPotion.<init>(EntityPotion.java:36) ~[zo.class:?]
        at dmillerw.bling.entity.EntitySplashPotion.<init>(EntitySplashPotion.java:25) ~[EntitySplashPotion.class:?]
        at dmillerw.bling.entity.EntitySplashPotion.<init>(EntitySplashPotion.java:41) ~[EntitySplashPotion.class:?]
        at dmillerw.bling.handler.EntityEventHandler.onEntityJoinWorld(EntityEventHandler.java:16) ~[EntityEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_56_EntityEventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122) ~[EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
        at net.minecraft.world.World.addEntity(World.java:1807) ~[ahb.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1698) ~[ahb.class:?]
        at net.minecraft.dispenser.BehaviorProjectileDispense.func_82487_b(BehaviorProjectileDispense.java:60) ~[kk.class:?]
        at net.minecraft.dispenser.BehaviorDefaultDispenseItem.func_82482_a(BehaviorDefaultDispenseItem.java:20) ~[cm.class:?]
        at net.minecraft.init.Bootstrap$5.func_82482_a(Bootstrap.java:98) ~[kv.class:?]
        at net.minecraft.block.BlockDispenser.func_149941_e(BlockDispenser.java:149) ~[akm.class:?]
        at net.minecraft.block.BlockDispenser.func_149674_a(BlockDispenser.java:183) ~[akm.class:?]
        at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:740) ~[mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:272) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) ~[MinecraftServer.class:?]
        ... 4 more
[17:04:25] [Server thread/ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException
        at net.minecraft.entity.projectile.EntityThrowable.<init>(EntityThrowable.java:53) ~[zk.class:?]
        at net.minecraft.entity.projectile.EntityPotion.<init>(EntityPotion.java:41) ~[zo.class:?]
        at net.minecraft.entity.projectile.EntityPotion.<init>(EntityPotion.java:36) ~[zo.class:?]
        at dmillerw.bling.entity.EntitySplashPotion.<init>(EntitySplashPotion.java:25) ~[EntitySplashPotion.class:?]
        at dmillerw.bling.entity.EntitySplashPotion.<init>(EntitySplashPotion.java:41) ~[EntitySplashPotion.class:?]
        at dmillerw.bling.handler.EntityEventHandler.onEntityJoinWorld(EntityEventHandler.java:16) ~[EntityEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_56_EntityEventHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122) ~[EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
        at net.minecraft.world.World.addEntity(World.java:1807) ~[ahb.class:?]
        at net.minecraft.world.World.func_72838_d(World.java:1698) ~[ahb.class:?]
        at net.minecraft.dispenser.BehaviorProjectileDispense.func_82487_b(BehaviorProjectileDispense.java:60) ~[kk.class:?]
        at net.minecraft.dispenser.BehaviorDefaultDispenseItem.func_82482_a(BehaviorDefaultDispenseItem.java:20) ~[cm.class:?]
        at net.minecraft.init.Bootstrap$5.func_82482_a(Bootstrap.java:98) ~[kv.class:?]
        at net.minecraft.block.BlockDispenser.func_149941_e(BlockDispenser.java:149) ~[akm.class:?]
        at net.minecraft.block.BlockDispenser.func_149674_a(BlockDispenser.java:183) ~[akm.class:?]
        at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:740) ~[mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:272) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_40]

```

**Comment by LemADEC** [comment]
Any update on this?

**Comment by Veirilli** [comment]
This crash occurs when a splash potion is launched from a dispenser. Also it seems to be related to #5, except in that issue it's a battlegear arrow that seems to mimic a dispenser launch. I've tested this with only baubles and alchemical bling installed to eliminate any other interaction. Also tested with just forge to make sure that wasn't this issue, with forge it worked fine.

Here is my crash log from the clean test: http://paste.ubuntu.com/9768301/
